- _data/navigation.yml
- _holistic-education/Academic Programmes/Information & Communications Technology.md
- _test/collection.yml
Hi Alvin,
I have updated our ICT staff table under information technology section at holistic education > academic programmes > Information & Communications Technology. Thank you
> Update file: Information & Communications Technology.md

- _co-curricular-activities/Performing Arts/Bowen Dance Club.md
- _co-curricular-activities/Performing Arts/Malay Dance.md
- _holistic-education/Student Leadership/Peer Support Leaders.md
- _holistic-education/Student Leadership/Student Leadership.md
- _holistic-education/Student Leadership/Tech Champions.md
- pages/privacy.md
- pages/terms-of-use.md
> 27 Apr Update 6

- pages/privacy.md
Update on Privacy Statement and Terms of Use
> 27 Apr  Update 7

- _school-information/School Matters/News & Events.md
> Web update 4 may update 2

- Resources/direct-school-admission/_posts/2023-05-03-post-Direct School Admission for 2024 cohort.md
- _signature-programmes/Direct School Admission.md
Pealse approve request . Thanks
> Pull request 4 May update 5

- _school-information/Bowen ParentLink/Join Bowen ParentLink.md
Please approved for the change of semi colon to colon after the word extract. Thank you
> Update on Bowen Parentlink

- _about-bowen/School Executive Committee.md
Please approve my request to change the error in the new VP's name
> Amend Mr chen name

- _school-information/School Matters/News & Events.md
- index.md
> TimeTable announcement update

- _holistic-education/Academic Programmes/Craft and Technology.md
- _holistic-education/Academic Programmes/English.md
- _holistic-education/Academic Programmes/Humanities.md
- _holistic-education/Academic Programmes/Mathematics.md
> Update 3 : remove teachers in Academic List

- _co-curricular-activities/Sports/Taekwondo.md
- _level-matters/Secondary 1/Cohort Theme & Form Teachers.md
> TKD update 8/9

- _about-bowen/School Executive Committee.md
- _holistic-education/Academic Programmes/Mother Tongue.md
> Web Update 

- _level-matters/Secondary 2/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 3/Cohort Theme & Form Teachers.md
> Update of Level Page

- pages/privacy.md
> approve test

- _level-matters/Secondary 1/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 2/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 3/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 4&5/Cohort Theme & Form Teachers.md
> Update 2 Webpage

- index.md
> 21/12 UPdate #1

- _school-information/Contact Information/Executive & Administrative Support Staff.md
> Webupdate #5

- _school-information/School Matters/News & Events.md
- index.md
> 28 DEC update #3

- _about-bowen/School Executive Committee.md
> 29 dec webupdate #1

- _school-information/Online Portals/Portals for Teachers.md
> Web update 29/12 #4

- _level-matters/Secondary 1/Class Timetables.md
- _school-information/School Matters/News & Events.md
- index.md
> Web update 2

- _level-matters/Secondary 1/Class Timetables.md
> Pls approve

- _co-curricular-activities/Performing Arts/Bowen Chorale.md
- _co-curricular-activities/Performing Arts/Drama Club.md
- _co-curricular-activities/Sports/Netball (Girls).md
Please approved the changes for CCA webpage:
1) Added Ms. Elliza pang on CCA Netball
2) Added Dorothy (2IC) on CCA choir
Thank you
> CCA updates April 2024

- index.md
> Quick link updates

- _about-bowen/Subject Heads & Senior and Lead Teachers.md
> SH page update

- _level-matters/Secondary 2/Assessment Schedules.md
- _level-matters/Secondary 3/Assessment Schedules.md
> Edited Title of Assessment pages for Sec 2 & 3

- _about-bowen/School Executive Committee.md
- _holistic-education/Academic Programmes/Mathematics.md
- _holistic-education/The Desired Bowenian.md
Update READY BE Poster on a different page (Desired Bowenian)
> Update READY BE Poster on a different page (Desired Bowenian)

- _level-matters/Secondary 1/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 2/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 3/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 4&5/Cohort Theme & Form Teachers.md
> Website change 21 NOv Update 2

- _about-bowen/The Principal's Foreword.md
> Web approval

- _about-bowen/Our Vision, Mission, Motto and Values.md
> Mission Vision Part 2

- index.md
> Homepage update

- index.md
> APPEAL FORM

- index.md
> Please approve

- _school-information/Online Portals/Portals for Teachers.md
Please approved the borken url of SSOE 2 link
> Repaired broken url 

- _school-information/Contact Information/Executive & Administrative Support Staff.md
Hi please approve the changes of removing mdm filzah and added Mr Yazid. Thank you.
> Executive & Administrative Support Staff udpates

- _holistic-education/CCE/Character and Citizenship Education.md
> FT Class updates

- _holistic-education/Academic Programmes/Craft and Technology.md
- _holistic-education/Academic Programmes/Mathematics.md
- _holistic-education/Academic Programmes/Science.md
> School Department updates

- _co-curricular-activities/CCAs.md
- _holistic-education/Academic Programmes/Mother Tongue.md
- _holistic-education/Academic Programmes/Physical Education.md
- _learning-with-technology/Learning with Technology.md
> Updated ICT Team and Mother tongue department

- _school-information/School Matters/Counselling & Learning Support.md
> update please approve

- _holistic-education/Academic Programmes/Mother Tongue.md
- _level-matters/Secondary 1/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 2/Cohort Theme & Form Teachers.md
Hi Alvin, please approve. thanks
> Updates on Mother Tongue department

- _about-bowen/Our Vision, Mission, Motto and Values.md
- _about-bowen/School Executive Committee.md
- _about-bowen/Subject Heads & Senior and Lead Teachers.md
- _holistic-education/The Desired Bowenian.md
- _level-matters/Secondary 1/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 2/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 3/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 4&5/Cohort Theme & Form Teachers.md
- _school-information/School Advisory Committee.md
> Update website SEC/SAC/ Level pages

- _school-information/School Matters/School Canteen Advertisement.md
> School Canteen Advertisment

- _school-information/Online Portals/Portals for Teachers.md
Please approve my changes. Thank you.
> Updating links for the time-off-request

- _school-information/School Matters/News & Events.md
> Spelling Error

- _about-bowen/School Executive Committee.md
- _about-bowen/Subject Heads & Senior and Lead Teachers.md
- _co-curricular-activities/Uniformed Groups/Boys Brigade.md
- _holistic-education/Academic Programmes/Music.md
- _level-matters/Secondary 1/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 2/Cohort Theme & Form Teachers.md
- _level-matters/Secondary 3/Cohort Theme & Form Teachers.md
> Update on personel

- _school-information/Online Portals/Portals for Students & Parents.md
> Remove Dead link
